---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import VNC playbook
  ansible.builtin.import_playbook: vnc.yml

- name: Import Assessor Portal composition playbook
  ansible.builtin.import_playbook: assessor_portal.yml

- name: Import extras playbook
  ansible.builtin.import_playbook: extras.yml

- name: Import cloud-init playbook
  ansible.builtin.import_playbook: cloud_init.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml
